[platformio]
default_envs =
  board-check--pico
  board-check--pico-w
  board-check--pico-2
  board-check--pico-2-w
  morse-beacon--pico
  morse-beacon--pico-w
  morse-beacon--pico-2
  morse-beacon--pico-2-w
  wifi-surveyor--pico-w
  wifi-surveyor--pico-2-w

[base]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#5d4561a05e3b212660ac6fdd3fbfb328d1988aa1
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0m
monitor_speed = 115200
build_flags = -std=gnu++17
build_unflags = -std=gnu++11

[board-pico]
board = rpipico
[board-pico-w]
board = rpipicow
[board-pico-2]
board = rpipico2
[board-pico-2-w]
board = rpipico2w

[board-check]
build_src_filter = -<*> +<pico_logic.cpp> +<apps/board-check.cpp>
[morse-beacon]
build_src_filter = -<*> +<pico_logic.cpp> +<apps/morse-beacon.cpp>
[wifi-surveyor]
build_src_filter = -<*> +<pico_logic.cpp> +<apps/wifi-surveyor.cpp>

[env:board-check--pico]
extends = base, board-pico, board-check
[env:board-check--pico-w]
extends = base, board-pico-w, board-check
[env:board-check--pico-2]
extends = base, board-pico-2, board-check
[env:board-check--pico-2-w]
extends = base, board-pico-2-w, board-check

[env:morse-beacon--pico]
extends = base, board-pico, morse-beacon
[env:morse-beacon--pico-w]
extends = base, board-pico-w, morse-beacon
[env:morse-beacon--pico-2]
extends = base, board-pico-2, morse-beacon
[env:morse-beacon--pico-2-w]
extends = base, board-pico-2-w, morse-beacon

[env:wifi-surveyor--pico-w]
extends = base, board-pico-w, wifi-surveyor
[env:wifi-surveyor--pico-2-w]
extends = base, board-pico-2-w, wifi-surveyor
