#include <Arduino.h>
#include <esp_random.h>

#include "app_support.h"
#include "lab_logic.h"

namespace {
LocalPortal portal;
constexpr const char* kAnswers[] = {
    "Yes. Suspiciously yes.", "No, and the board seems confident.", "Ask again after coffee.",
    "The silicon says maybe.", "Absolutely not on a Tuesday.", "Proceed, but look casual.",
    "Future you has concerns.", "Tiny computer approves.",
};

void serveAnswer() {
    const String kind = portal.server.arg("kind");
    String answer;
    if (kind == "coin") {
        answer = boundedChoice(esp_random(), 2) == 0 ? "Heads" : "Tails";
    } else if (kind == "dice") {
        answer = String(boundedChoice(esp_random(), 6) + 1);
    } else {
        answer = kAnswers[boundedChoice(esp_random(), sizeof(kAnswers) / sizeof(kAnswers[0]))];
    }
    portal.server.send(200, "text/plain; charset=utf-8", answer);
}

void serveHome() {
    String body = "<p class=muted>Join <code>ESP32-Decision-Oracle</code>. All decisions are generated by hardware randomness and carry no warranty.</p>";
    body += "<div class='card' style='text-align:center'><h2 id=answer>Consult the tiny computer.</h2><div class=grid><button data-k=coin>Flip coin</button><button data-k=dice>Roll d6</button><button class=primary data-k=advice>Questionable advice</button></div></div>";
    const String script = "const a=document.querySelector('#answer');document.querySelectorAll('[data-k]').forEach(b=>b.onclick=async()=>{a.textContent='Thinking very small thoughts…';a.textContent=await fetch('./api/ask?kind='+b.dataset.k).then(r=>r.text())});";
    portal.server.send(200, "text/html; charset=utf-8", pageShell("Decision Oracle", body, script));
}
}  // namespace

void setup() {
    Serial.begin(115200);
    delay(200);
    portal.server.on("/", HTTP_GET, serveHome);
    portal.server.on("/api/ask", HTTP_GET, serveAnswer);
    portal.begin("ESP32-Decision-Oracle");
}

void loop() {
    portal.handle();
    delay(2);
}
