[platformio]
default_envs = esp32-c6-devkitc-1

[env]
lib_deps =
  h2zero/NimBLE-Arduino@2.5.1
  knolleary/PubSubClient@2.8.0
  bblanchon/ArduinoJson@7.4.3
build_flags =
  -std=gnu++17
build_unflags =
  -std=gnu++11

[env:esp32-c6-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<device_registry.cpp> +<presence_tracker.cpp>
